// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Crossrail.ObservationForm.DataLayer.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class ObservationCategoryReferenceOrderIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ObservationCategoryReferenceOrderIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201312091120220_ObservationCategoryReferenceOrderIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
